### PR TITLE
Is it necessary to make assumptions about motivations?

### PR DESCRIPTION
**Pull request by tomchor**
This is a minor point (and a bit philosophical) but do we need to assume that everyone that goes through the group is fascinated (which is a pretty strong word imo) with the topic? This is the case for me at this moment, but I'd say it might it not be the case for everyone at all times.

So this PR proposes to simply exclude that sentence. But I'm interested also in hearing everyone else's opinions

@team

### CODE REVIEW

**Comment by wenegrat** [comment]
This is an interesting point, that I'd like to think about and discuss a bit more before merging. 

I think it's important to convey the need for some intrinsic motivation in order to be successful (ie. that success in science requires some deep _interest_ in the topic you are working on), but agree that 'fascinated' may not be the best word.

**Comment by tomchor** [comment]
> This is an interesting point, that I'd like to think about and discuss a bit more before merging.

That's fine. Just to be clear, from my experience only a small minority of PRs actually get merged without any changes. Some get rejected, and most get modified before merging.
So feel free to make changes of your own to this PR also before merging if you feel it's necessary. (or even reject it completely...)

> I think it's important to convey the need for some intrinsic motivation in order to be successful (ie. that success in science requires some deep _interest_ in the topic you are working on), but agree that 'fascinated' may not be the best word.

Agreed!

**Comment by wenegrat** [comment]
The latest commit (f0c657e85b4903daa877fd2c437f3ef02f4a37cc) includes some changes in wording that I think address this. I appreciate you bringing this up, as it definitely caused me to spend some time thinking about this question: 'What is the expectation around _why_ we are here doing this work?'

It made me realize two things:
1) That it is not necessarily the case (or necessarily always true) that we are motivated primarily by our research topic.
2) That it is my belief that in order to be successful in graduate school and beyond you need to work on things you are excited and intrinsically motivated by.

These aren't mutually exclusive, but the prior document didn't really cover the complexity. Maybe the new version is better.

**Comment by tomchor** [comment]
Nice! I agree the latest version addresses the issue I raised here so I'm closing this PR for now.

**Pull request closed without merging**
